#!/bin/bash -l
#SBATCH -N 1              # you'll never need more than 1 node for the serial code
#SBATCH -t 00:20:00       # adjust the amount of time as necessary
#SBATCH -J auto-serial
#SBATCH -o auto-serial.%j.stdout
#SBATCH -e auto-serial.%j.error

rm serial3.txt
 ./serial -n 5000 -no -s serial3.txt
 ./serial -n 15000 -no -s serial3.txt
 ./serial -n 20000 -no -s serial3.txt
 ./serial -n 40000 -no -s serial3.txt
 ./serial -n 60000 -no -s serial3.txt
./autograder -v serial -s serial3.txt
