#!/bin/bash -l
#SBATCH -N 8			  # adjust the number of nodes per test (e.g. start with 1, 2, ...)
#SBATCH -t 00:20:00		  # adjust the amount of time as necessary
#SBATCH -J auto-mpi32
#SBATCH -o auto-mpi32.%j.stdout
#SBATCH -e auto-mpi32.%j.error

rm mpi2.txt
mpirun -n 1  ./serial -n 500 -no -s mpi2.txt
mpirun -n 1  ./mpi -p 1 -n 500 -no -s mpi2.txt
mpirun -n 2  ./mpi -p 2 -n 500 -no -s mpi2.txt
mpirun -n 4  ./mpi -p 4 -n 500 -no -s mpi2.txt
mpirun -n 6  ./mpi -p 6 -n 500 -no -s mpi2.txt
mpirun -n 8  ./mpi -p 8 -n 500 -no -s mpi2.txt
mpirun -n 2  ./mpi -p 2 -n 1000 -no -s mpi2.txt
mpirun -n 4  ./mpi -p 4 -n 2000 -no -s mpi2.txt
mpirun -n 6  ./mpi -p 6 -n 3000 -no -s mpi2.txt
mpirun -n 8  ./mpi -p 8 -n 6000 -no -s mpi2.txt
./autograder -v mpi -s mpi2.txt
