#!/bin/bash -l
#SBATCH -N 8         # adjust the number of nodes per test (e.g. start with 1, 2, ...)

#SBATCH -t 00:10:00   # adjust the amount of time as necessary
#SBATCH -J mpi8
#SBATCH -o mpi8.%j.stdout
#SBATCH -e mpi8.%j.error

mpirun -n 8  ./mpi -p 8 -n 500 -no -s mpi3.txt  # adjust -n here as well
