#!/bin/bash -l
#SBATCH -N 1                # you'll never need more than 1 node for the serial code
#SBATCH -t 00:20:00         # adjust the amount of time as necessary
#SBATCH -J auto-openmp32
#SBATCH -o auto-openmp32.%j.stdout
#SBATCH -e auto-openmp32.%j.error

rm openmp3.txt
./serial -n 5000 -no -s openmp3.txt
export OMP_NUM_THREADS=1
./openmp -n 5000 -no -s openmp3.txt
export OMP_NUM_THREADS=2
./openmp -n 5000 -no -s openmp3.txt
export OMP_NUM_THREADS=4
./openmp -n 5000 -no -s openmp3.txt
export OMP_NUM_THREADS=6
./openmp -n 5000 -no -s openmp3.txt
export OMP_NUM_THREADS=12
./openmp -n 5000 -no -s openmp3.txt
export OMP_NUM_THREADS=18
./openmp -n 5000 -no -s openmp3.txt
export OMP_NUM_THREADS=24
./openmp -n 5000 -no -s openmp3.txt
export OMP_NUM_THREADS=32
./openmp -n 5000 -no -s openmp3.txt
export OMP_NUM_THREADS=2
./openmp -n 10000 -no -s openmp3.txt
export OMP_NUM_THREADS=4
./openmp -n 20000 -no -s openmp3.txt
export OMP_NUM_THREADS=6
./openmp -n 30000 -no -s openmp3.txt
export OMP_NUM_THREADS=12
./openmp -n 60000 -no -s openmp3.txt
export OMP_NUM_THREADS=18
./openmp -n 90000 -no -s openmp3.txt
export OMP_NUM_THREADS=24
./openmp -n 120000 -no -s openmp3.txt
export OMP_NUM_THREADS=32
./openmp -n 160000 -no -s openmp3.txt
./autograder -v openmp -s openmp3.txt
