function createlegend(axes1)
%CREATELEGEND(axes1)
%  AXES1:  legend axes

%  Auto-generated by MATLAB on 30-Apr-2018 10:04:53

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.150655021834061 0.700000000000001 0.164847161572052 0.185119047619055]);

