function createlegend(axes1)
%CREATELEGEND(axes1)
%  AXES1:  legend axes

%  Auto-generated by MATLAB on 22-Feb-2018 14:24:11

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.174750467872738 0.635036496350365 0.147301933873987 0.217644247480015],...
    'FontSize',12);

