#!/bin/bash -l
#SBATCH -N 1              # you'll never need more than 1 node for the serial code
#SBATCH -t 00:20:00       # adjust the amount of time as necessary
#SBATCH -J auto-serial
#SBATCH -o auto-serial.%j.stdout
#SBATCH -e auto-serial.%j.error

rm serial-v2.txt
 ./serial-v2 -n 500 -no -s serial-v2.txt
 ./serial-v2 -n 1000 -no -s serial-v2.txt
 ./serial-v2 -n 2000 -no -s serial-v2.txt
 ./serial-v2 -n 4000 -no -s serial-v2.txt

./autograderv2 -v serial-v2 -s serial-v2.txt
